# Generated by Django 2.0.6 on 2018-06-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('netid', models.CharField(help_text='Use your Princeton-issued netID.', max_length=40, unique=True)),
                ('email', models.EmailField(help_text='Please use Princeton email.', max_length=255, unique=True)),
                ('full_name', models.CharField(help_text='Your full name.', max_length=4)),
                ('class_year', models.CharField(help_text='Your class year, <em>YYYY</em>', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
