# Generated by Django 2.0.6 on 2018-06-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(help_text='Your full name.', max_length=40),
        ),
    ]
