# Generated by Django 2.0.6 on 2018-06-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseid',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
