# Generated by Django 2.0.6 on 2018-06-19 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses_groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='groupid',
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
