# Generated by Django 2.0.6 on 2018-07-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('netid', models.CharField(help_text='Use your Princeton-issued netID.', max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='NetID')),
                ('email', models.CharField(max_length=100)),
                ('full_name', models.CharField(help_text='Your full name.', max_length=40, verbose_name='Full name')),
                ('class_year', models.CharField(help_text='Your class year, <em>YYYY</em>', max_length=4, verbose_name='Class Year')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['full_name'], name='users_user_full_na_243c3c_idx'),
        ),
    ]
