# Generated by Django 2.0.6 on 2018-07-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.BinaryField(default=b'\x00', max_length=21),
            preserve_default=False,
        ),
    ]
