# Generated by Django 2.0.6 on 2018-06-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='1@princeton.edu', max_length=100),
            preserve_default=False,
        ),
    ]
