# Generated by Django 2.0.6 on 2018-07-10 18:08

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='availability',
            field=users.models.AvailField(),
        ),
    ]
